// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDidZ0SvYL7fYH321oskt1kfYULYR4FrVI',
    appId: '1:289760610648:web:ceeb68046f4eeb8d78bd2d',
    messagingSenderId: '289760610648',
    projectId: 'nutrimate-4962',
    authDomain: 'nutrimate-4962.firebaseapp.com',
    storageBucket: 'nutrimate-4962.firebasestorage.app',
    measurementId: 'G-KT1YEDYF0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtWOEKItK6ARyISBb3ZsxmWkLjAXGzQzA',
    appId: '1:289760610648:android:b2d7631ce7c116aa78bd2d',
    messagingSenderId: '289760610648',
    projectId: 'nutrimate-4962',
    storageBucket: 'nutrimate-4962.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHKSe37vqK_A5XhUy4fHrbxmg5piSJxto',
    appId: '1:289760610648:ios:ed99947fda0f141478bd2d',
    messagingSenderId: '289760610648',
    projectId: 'nutrimate-4962',
    storageBucket: 'nutrimate-4962.firebasestorage.app',
    iosBundleId: 'com.example.nutriMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHKSe37vqK_A5XhUy4fHrbxmg5piSJxto',
    appId: '1:289760610648:ios:ed99947fda0f141478bd2d',
    messagingSenderId: '289760610648',
    projectId: 'nutrimate-4962',
    storageBucket: 'nutrimate-4962.firebasestorage.app',
    iosBundleId: 'com.example.nutriMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDidZ0SvYL7fYH321oskt1kfYULYR4FrVI',
    appId: '1:289760610648:web:584d68221f82e11678bd2d',
    messagingSenderId: '289760610648',
    projectId: 'nutrimate-4962',
    authDomain: 'nutrimate-4962.firebaseapp.com',
    storageBucket: 'nutrimate-4962.firebasestorage.app',
    measurementId: 'G-48QLBE8E6Z',
  );
}
